# Generated by Django 2.1.2 on 2018-10-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
