# Generated by Django 2.1.2 on 2018-10-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0008_auto_20181004_0715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
