# Generated by Django 2.1.2 on 2018-10-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0013_auto_20181006_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
